# fly.toml app configuration file generated for registrxe on 2024-12-17T09:23:25-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'anu-registry'

[build]
image = 'registry:2'

[experimental]
#cmd = ["sleep", "inf"]

[env]
REGISTRY_STORAGE = "s3"
REGISTRY_STORAGE_S3_REGION = "auto"
REGISTRY_STORAGE_S3_REGIONENDPOINT = "https://fly.storage.tigris.dev"
REGISTRY_STORAGE_S3_FORCEPATHSTYLE = "false"
REGISTRY_STORAGE_S3_ENCRYPT = "false"
REGISTRY_STORAGE_S3_SECURE = "true"
REGISTRY_STORAGE_S3_V4AUTH = "true"
REGISTRY_STORAGE_S3_CHUNKSIZE = "5242880"
REGISTRY_STORAGE_S3_ROOTDIRECTORY = "/"
REGISTRY_AUTH = "token"
REGISTRY_AUTH_TOKEN_SERVICE = "Authentication"
REGISTRY_AUTH_TOKEN_ISSUER = "Tigris Anu"
REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE = "/data/anu.pem"
REGISTRY_HTTP_DEBUG_ADDR = ":5001"
REGISTRY_HTTP_DEBUG_PROMETHEUS_ENABLED = "true"
REGISTRY_HTTP_DEBUG_PROMETHEUS_PATH = "/metrics"

[[files]]
guest_path = "/data/anu.pem"
secret_name = "JWT_CERT_B64"

[[metrics]]
port = 5001
path = "/metrics"

[[services]]
protocol = 'tcp'
internal_port = 5000
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[services.http_checks]]
interval = 10000
grace_period = "5s"
method = "GET"
path = "/"
protocol = "http"
timeout = 2000
tls_skip_verify = false

[[services.ports]]
port = 80
handlers = ['http']
force_https = true

[[services.ports]]
port = 443
handlers = ['tls', 'http']

[services.concurrency]
type = 'connections'
hard_limit = 1000
soft_limit = 750
